CREATE  TABLE IF NOT EXISTS  CURRENCY (
    en CHAR(10) NOT NULL  PRIMARY KEY,
    zh CHAR(10) NOT NULL
    );
INSERT INTO CURRENCY (en, zh) VALUES ('USD', '美元');
INSERT INTO CURRENCY (en, zh) VALUES ('GBP', '英鎊');
INSERT INTO CURRENCY (en, zh) VALUES ('EUR', '歐元');